version: '2'
services:

  redis:
    image: redis:latest
    restart: always

  ethereum_node:
    image: ethereum/client-go:stable
    restart: always
    entrypoint: geth --rpc --rpcaddr 0.0.0.0 --rpcapi eth,personal
    volumes:
      - "~/.ethereum:/root/.ethereum"         # blockchain client data directory

  minter-service:
    build:
      context: .
    depends_on:
      - redis
      - ethereum_node
    ports:
      - "8000:8000"                           # minter-service port (change first digit)
    volumes:
      - "/data:/app/data"                     # minter-service data directory
      - "/minter.conf:/app/conf/minter.conf"  # config file

